name: run data_collector.py

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 0 * * 1' # At 00:00 on Monday

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner
        with:
          ref: data

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script # run data_collector.py
        env:
          SUNSYNK_USERNAME: ${{ secrets.SUNSYNK_USERNAME }}
          SUNSYNK_PASSWORD: ${{ secrets.SUNSYNK_PASSWORD }}
        run: python data_collector.py
          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated data" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: data

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!